### ISSUE TITLE
launch still failed

### ISSUE THREAD

**Issue by seekdestiny** [team-binary/carnd-capstone#7]
auto-starting new master
process[master]: started with pid [16170]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d0b32724-5810-11e9-ad87-000c295f128a
process[rosout-1]: started with pid [16183]
started core service [/rosout]
process[styx_server-2]: started with pid [16194]
process[dbw_node-3]: started with pid [16201]
process[waypoint_loader-4]: started with pid [16202]
process[pure_pursuit-5]: started with pid [16203]
Traceback (most recent call last):
File "/home/jifeiqian/Projects/udacity-CarND/carnd-capstone/ros/src/styx/server.py", line 3, in 
import socketio
ImportError: No module named socketio
process[waypoint_updater-6]: started with pid [16204]
process[tl_detector-7]: started with pid [16215]
[styx_server-2] process has died [pid 16194, exit code 1, cmd /home/jifeiqian/Projects/udacity-CarND/carnd-capstone/ros/src/styx/server.py __name:=styx_server __log:=/home/jifeiqian/.ros/log/d0b32724-5810-11e9-ad87-000c295f128a/styx_server-2.log].
log file: /home/jifeiqian/.ros/log/d0b32724-5810-11e9-ad87-000c295f128a/styx_server-2*.log
[INFO] [1554516487.599633]: WPUpdater: Got initial waypoints

Hi Aaaron,

I use the new code to test but it still has some issues.
I can make sure I have already installed socketio by
sudo -H pip install python-socketio

Can you please take a look at it?

thanks,
jeff

**Comment by aaronhma** [comment]
Did you install the dependecies in the requirements.txt？

**Comment by seekdestiny** [comment]
Sure. I follow each step in readme exactly.
I also search these issues in knowledge hub. I feel there are more steps missing in the readme to
guarantee a successful launch.

**Comment by seekdestiny** [comment]
I give native installation now.
